### ISSUE TITLE
Please move all issues from this repo to the istio/istio repo.

### ISSUE THREAD

**Issue by geeknoid** [istio/cni#107]
Open every issue, and select Transfer Issue in the bottom right.

Once all issues are transferred, we'll disable the Issues feature in this repo.

**Comment by rlenglet** [comment]
@geeknoid Can you please create an "area/cni" label in istio/istio, to use on all those issues?

**Comment by rlenglet** [comment]
Nevermind, I created area/networking/cni.

**Comment by venilnoronha** [comment]
@geeknoid all issues have been transferred. We can disable Issues for this repo.

**Comment by geeknoid** [comment]
Thanks.
