### ISSUE TITLE
cni config file may be overwritten 

### ISSUE THREAD

**Issue by baodongli** [istio/cni#22]
Since istio-cni plugin doesn't work on its own, and depends on other CNI plugins to perform interface plumbing and IPAM, the cni config file (at /etc/cni/net.d) may be overwritten by other CNI plugins' daemons due to, e.g., restart of the daemons. Consequently, kubelet will not invoke istio-cni plugin anymore.

**Comment by jwendell** [comment]
A proper solution would be a change in the CNI spec, allowing multiple config files. https://github.com/containernetworking/cni/issues/595

In the meantime, I believe one possible solution would be to monitor that file for changes and re-apply our configuration whenever it's gone. One more point to https://github.com/istio/cni/issues/21 :)

**Comment by john-a-joyce** [comment]
This is fixed via:  https://github.com/istio/cni/pull/83
