### ISSUE TITLE
Validate the CNI with an istio-remote deployment

### ISSUE THREAD

**Issue by john-a-joyce** [istio/cni#39]
Arguably this issue should be create in istio/istio.  The work is to validate that the Helm options and charts added for istio single cluster uses cases work properly in a multicluster environment where istio-remote is used.

**Comment by venilnoronha** [comment]
Issue moved to [istio/istio #14322](https://github.com/istio/istio/issues/14322) via [**ZenHub**](https://www.zenhub.com/)
