### ISSUE TITLE
Refactor istio-cni according to design

### ISSUE THREAD

**Issue by tiswanso** [istio/cni#41]
This is to track the refactor effort for getting the code organized according to the design spec.

https://docs.google.com/document/d/1B5gGvdlZEfk5oAL8Qx8NdRKDYb3YlGphJoQLhwPBXYw/edit?usp=sharing

**Comment by venilnoronha** [comment]
Issue moved to [istio/istio #14323](https://github.com/istio/istio/issues/14323) via [**ZenHub**](https://www.zenhub.com/)
