### ISSUE TITLE
Add Istio initContainers enable_coredump logic via CNI

### ISSUE THREAD

**Issue by tiswanso** [istio/cni#44]
During review of https://github.com/istio/istio/pull/9461 the point was raised about also applying the enable coredump settings via the CNI.  

See the Istio sidecar  inject template logic for the `enable-core-dump` initContainer.

**Comment by venilnoronha** [comment]
Issue moved to [istio/istio #14319](https://github.com/istio/istio/issues/14319) via [**ZenHub**](https://www.zenhub.com/)
