### ISSUE TITLE
syntax of dockerfile is wrong

### ISSUE THREAD

**Issue by sdake** [istio/cni#48]
see https://github.com/istio/cni/blob/master/deployments/kubernetes/Dockerfile.install-cni#L3

Also, please use ubuntu rather than Alpine Linux.  I'm not sure how this dockerfile is used, but as a project Istio should avoid distro proliferation.

**Comment by venilnoronha** [comment]
Issue moved to [istio/istio #14320](https://github.com/istio/istio/issues/14320) via [**ZenHub**](https://www.zenhub.com/)
