### ISSUE TITLE
Envoy port is not configurable

### ISSUE THREAD

**Issue by luksa** [istio/cni#84]
Looking at the code, I don't see a way to override the default redirect port (15001). We should introduce a ConfigMap to make the port configurable (as it is when using the init container - see MeshConfig.ProxyListenPort)

**Comment by luksa** [comment]
The same goes for `.ProxyConfig.InterceptionMode`

**Comment by tiswanso** [comment]
For intercept mode the pod annotation can set this:  `sidecar.istio.io/interceptionMode`

**Comment by venilnoronha** [comment]
Issue moved to [istio/istio #14317](https://github.com/istio/istio/issues/14317) via [**ZenHub**](https://www.zenhub.com/)
