### ISSUE TITLE
Make this CNI compliant with ipv6

### ISSUE THREAD

**Issue by alexlovelltroy** [istio/cni#95]
This CNI only appears to manage the iptables associated with ipv4.  Kubernetes is broadly moving to ipv6 and dual-stack support.  Adding an issue to track ipv6 needs and suggestions.

**Comment by john-a-joyce** [comment]
@alexlovelltroy - some of my peers at Cisco were championing the K8s dual stack IPv6 support so I am well aware of the status.   Additionally we had done some work in Istio to determine IPv6 Gaps,  but did not complete the work.  Recently sbezverk has been trying to fix some of the gaps that in this regard.   We would love to ensure that the CNI is ahead of both K8s and Istio wrt to IPv6 support so if this is an area you can help with that would be much appreciated.

**Comment by alexlovelltroy** [comment]
Having explored the codebase a bit, I don't think I'm ready to contribute code, but I'm happy to do triage, review PRs, write/update docs.

**Comment by venilnoronha** [comment]
Issue moved to [istio/istio #14318](https://github.com/istio/istio/issues/14318) via [**ZenHub**](https://www.zenhub.com/)
